name: Deploy Angular App to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Ensure this matches the Azure Web App runtime

    - name: Install dependencies
      run: npm install

    - name: Build Angular application
      run: npm run build -- --configuration production

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: "angular-azure-app"  # Ensure it matches the Azure Web App name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: dist/angular-azure-app
